image: node:latest

stages:
  - build

before_script:
  - apt-get update
  - apt-get install zip

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - export
    - npm ci
    - npm run build
    - mv dist foundryvtt-pf2e-lang-es
    - zip foundryvtt-pf2e-lant-es.zip -r foundryvtt-pf2e-lang-es
  artifacts:
    paths:
      - module.json
      - foundryvtt-pf2e-lang-es.zip
